import type { Metadata } from "next";
import { Kelly_Slab, Prosto_One } from "next/font/google";
import "./globals.css";
// import HeadStyles from "./components/HeadStyles";
import CartWrapper from "../components/CartWrapper";
import ExternalResources from "../components/ExternalResources";
// import MedusaProvider from "../contexts/MedusaProvider";

// Импорты компонентов
import "./styles/components/header.css";
import "./styles/components/footer.css";
import "./styles/components/buttons.css";
import "./styles/components/product-card.css";
import "./styles/components/image-modal.css";
// import "./styles/components/article-card.css"; // удалено вместе с карточками статей
import "./styles/components/review-card.css";

// Импорты страниц
import "./styles/pages/home.css";
import "./styles/pages/product-detail.css";
import "./styles/pages/about.css";
import "./styles/pages/delivery.css";
import "./styles/pages/checkout-page.css";

// Импорты админ панели (подключаются только на страницах админ панели)
// import "./styles/admin/admin-base.css";
// import "./styles/admin/admin-dashboard.css";
// import "./styles/admin/admin-products.css";
// import "./styles/admin/admin-forms.css";

// Импорты адаптивных стилей
import "./styles/responsive/mobile.css";
import "./styles/responsive/tablet.css";
import "./styles/responsive/desktop.css";

// Определяем шрифты Kelly Slab и Prosto One
const kellySlab = Kelly_Slab({
  weight: ["400"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-kelly-slab",
});

const prostoOne = Prosto_One({
  weight: ["400"], // Prosto One имеет только один вес
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-prosto-one",
});

export const metadata: Metadata = {
  title: "BioMorphX - Научные добавки премиум-класса",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru"> {/* Устанавливаем язык на русский */}
      <head>
        <link rel="preload" href="/img/L-Threonine.png" as="image" />
        <link rel="preload" href="/img/L-Proline.png" as="image" />
        <link rel="preload" href="/img/L-Phenilalanine.png" as="image" />
        <link rel="preload" href="/img/L-valine.png" as="image" />
        <link rel="preload" href="/img/L-Leucine.png" as="image" />
        <link rel="preload" href="/img/L-Isoleucine.png" as="image" />
        <link rel="preload" href="/img/L-Cysteine.png" as="image" />
        <link rel="preload" href="/img/Calcium-D-Gluconate.png" as="image" />
        <link rel="preload" href="/img/Postassium Citrate.png" as="image" />
        <link rel="preload" href="/img/Zinc.png" as="image" />
        <link rel="preload" href="/img/Sodium Alginate.png" as="image" />
      </head>
      <body className={`${kellySlab.variable} ${prostoOne.variable}`}> {/* Применяем переменные шрифтов */}
        <ExternalResources />
        {/* <MedusaProvider> */}
          <CartWrapper>
            {children}
          </CartWrapper>
        {/* </MedusaProvider> */}
      </body>
    </html>
  );
}
