import type { Metadata } from "next";
import { Kelly_Slab, Prosto_One } from "next/font/google";
import "./globals.css";
import HeadStyles from "./components/HeadStyles";
import CartWrapper from "../components/CartWrapper";
import MedusaProvider from "../contexts/MedusaProvider";

// Импорты компонентов
import "./styles/components/header.css";
import "./styles/components/footer.css";
import "./styles/components/buttons.css";
import "./styles/components/product-card.css";
import "./styles/components/image-modal.css";
// import "./styles/components/article-card.css"; // удалено вместе с карточками статей
import "./styles/components/review-card.css";

// Импорты страниц
import "./styles/pages/home.css";
import "./styles/pages/product-detail.css";
import "./styles/pages/about.css";
import "./styles/pages/delivery.css";
import "./styles/pages/checkout-page.css";

// Импорты админ панели (подключаются только на страницах админ панели)
// import "./styles/admin/admin-base.css";
// import "./styles/admin/admin-dashboard.css";
// import "./styles/admin/admin-products.css";
// import "./styles/admin/admin-forms.css";

// Импорты адаптивных стилей
import "./styles/responsive/mobile.css";
import "./styles/responsive/tablet.css";
import "./styles/responsive/desktop.css";

// Определяем шрифты Kelly Slab и Prosto One
const kellySlab = Kelly_Slab({
  weight: ["400"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-kelly-slab",
});

const prostoOne = Prosto_One({
  weight: ["400"], // Prosto One имеет только один вес
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-prosto-one",
});

export const metadata: Metadata = {
  title: "BioMorphX - Научные добавки премиум-класса",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
  other: {
    'font-awesome': 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css',
    'google-fonts-preconnect': 'https://fonts.googleapis.com',
    'google-fonts-gstatic': 'https://fonts.gstatic.com',
    'montserrat-alternates': 'https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru"> {/* Устанавливаем язык на русский */}
      <head>
        <link rel="stylesheet" href="/node_modules/@fortawesome/fontawesome-free/css/all.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </head>
      <body className={`${kellySlab.variable} ${prostoOne.variable}`}> {/* Применяем переменные шрифтов */}
        <HeadStyles />
        <MedusaProvider>
          <CartWrapper>
            {children}
          </CartWrapper>
        </MedusaProvider>
      </body>
    </html>
  );
}
